apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: grafana/tempo
  repo: https://github.com/grafana/helm-charts/
  version: "2.6.1"
  releaseName: tempo
  namespace: monitoring
  valuesFile: values.yaml
  
