apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polar-bookshop-ingress
spec:
  rules:
   - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: edge-service-stable
              port:
                number: 80                                
---
apiVersion: v1
data:
  allow-backend-server-header: "true"
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration