apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

resources:
- ../../base

namespace: polarbook-development

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
       name: order-service-rollout
      spec:
        template:
          spec:
            containers:
              - name: order-service-container
                env:
                  - name: SPRING_PROFILES_ACTIVE
                    value: production
                  - name: JAVA_TOOL_OPTIONS
                    value: -javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.6.0.jar
                  - name: OTEL_SERVICE_NAME
                    value: order-service           
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: http://tempo.monitoring-polarbook-development.svc.cluster.local:4318
                  - name: OTEL_METRICS_EXPORTER
                    value: none
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
       name: order-service-rollout
      spec:
        replicas: 2

images:
- name: ghcr.io/upen28/polar-bookshop/order-service
  newTag: 00487e9bb18cf44bc0d8824cadd6aa11a66f7d57

configMapGenerator:
  - name: order-configmap
    files:
      - application.yml
    options:
      labels:
        app: order-service
        
secretGenerator:
-  name: order-secrets
   literals:
   - spring.r2dbc.password=sxctWoXesH 