apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: monitoring-polarbook
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      releaseName: loki-stack
      values: |
        grafana:
          enabled: true
        prometheus:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring-polarbook
  