apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-service-development
  namespace: argocd  
spec:
  project: polarbook-development
  source:
    repoURL: https://github.com/upen28/polar-deployment-2.git
    path: kubernetes/applications/edge-service/development
    targetRevision: HEAD    
  destination:
    server: https://kubernetes.default.svc
    namespace: polarbook-development
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
