apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service-development 
  namespace: argocd 
spec:
  project: polarbook-development
  source:
    repoURL: https://github.com/upen28/order-service-gitops.git
    path: kubernetes/order-service/dev
    targetRevision: HEAD    
  destination:
    server: https://kubernetes.default.svc
    namespace: polarbook-development
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
