apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
   name: catalog-service-rollout
   labels:
      app: catalog-service-rollout
spec:
   replicas: 1
   strategy:
      canary:
         maxSurge: 25%
         maxUnavailable: 0
         steps:
         -  setWeight: 10
         -  pause: {}
   selector:
      matchLabels:
         app: catalog-service
   template:
      metadata:
         labels:
            app: catalog-service
         annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: /actuator/prometheus
            prometheus.io/port: '9001'
      spec:
         containers:
         -  name: catalog-service-container
            image: ghcr.io/upen28/polar-bookshop/catalog-service:latest
            imagePullPolicy: Always
            ports:
            -  containerPort: 9001
            livenessProbe:
               httpGet:
                  path: /actuator/health/liveness
                  port: 9001
               initialDelaySeconds: 15
               periodSeconds: 30
            readinessProbe:
               httpGet:
                  path: /actuator/health/readiness
                  port: 9001
               initialDelaySeconds: 15
               periodSeconds: 30
            volumeMounts:
            -  name: catalog-secrets-volume
               mountPath: /workspace/secrets/postgres
            -  name: catalog-configmap-volume
               mountPath: /workspace/config
         volumes:
         -  name: catalog-secrets-volume
            secret:
               secretName: catalog-secrets
         -  name: catalog-configmap-volume
            configMap:
               name: catalog-configmap
---
apiVersion: v1
kind: Service
metadata:
   name: catalog-service
   labels:
      app: catalog-service
spec:
   selector:
      app: catalog-service
   ports:
   -  protocol: TCP
      port: 80
      targetPort: 9001