apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog-service-rollout
  labels:
    app: catalog-service-rollout
spec:
  replicas: 1
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause: {}
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
    spec:     
      containers:
        - name: catalog-service-container
          image: ghcr.io/upen28/polar-bookshop/catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: spring.datasource.url
              value: jdbc:postgresql://my-release-postgresql:5432/polardb_catalog
            - name: spring.datasource.username
              value: postgres
            - name: spring.datasource.password
              value: sxctWoXesH
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.6.0.jar
            - name: OTEL_SERVICE_NAME
              value: edge-service           
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.monitoring.svc.cluster.local:4318
            - name: OTEL_METRICS_EXPORTER
              value: none     
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 60000
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 15
            periodSeconds: 60000     
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001