apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-service
  namespace: argocd
spec:
  project: polarbook-production
  source:
    repoURL: https://github.com/upen28/catalog-service-gitops.git
    path: kubernetes/catalog-service/main
    targetRevision: HEAD    
  destination:
    server: https://kubernetes.default.svc
    namespace: polarbook-production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      
