apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-service
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/upen28/edge-service.git
